name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        stable: false
    
    - name: Disable Modules
      run: export GO111MODULE=off

    - name: Build
      run: |
           go get github.com/snukone/trace
           go get github.com/gorilla/websocket
           go build -v ./...

    - name: Test
      run: go test -v ./...
